spring:
  application:
    name: bienestarbd

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 30000

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30m

  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
    from: ${MAIL_USER}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

app:
  jwt:
    secret: S2RjYmxFM2ZsYVZXaWRTa0VMMEdmWjZYZUV4dzRjY0NacmlvT0VnT2NVRWlDTzNv
    expirationMs: 86400000
    refreshExpirationMs: 604800000

  cors:
    allowed-origins: >
      http://localhost:5173,
      http://localhost:8080,
      http://192.168.18.20:5173,
      https://bienestar-front.onrender.com/
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD
    allowed-headers: >
      Authorization,Content-Type,X-Requested-With,
      Accept,Origin,Access-Control-Request-Method,
      Access-Control-Request-Headers
    exposed-headers: Authorization,Content-Disposition,Content-Type,X-Requested-With