server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bienestar_software
    username: postgressql
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.springframework: INFO
      com.unicolombo.bienestar: DEBUG